AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') 

Role.create(:title=>"ADMIN")
Role.create(:title=>"PESADOR")
Role.create(:title=>"PULPERO")
Role.create(:title=>"PILA")
Role.create(:title=>"PATIO")
Role.create(:title=>"BODEGA")
Role.create(:title=>"TRANSPORTACION")
Role.create(:title=>"CATADOR")